version: "3"

services:
  web:
    image: nginx:$NGINX_TAG
    ports:
      - '8080:80'
    volumes:
      - "./drupal/web:/var/www/html"
      - "./drupal/nginx.conf:/etc/nginx/conf.d/default.conf"
    links:
        - php

  php:
    image: drupal:$DRUPAL_TAG
    volumes:
      - "./drupal/web:/var/www/html"

  mysql:
      image: mysql:$MYSQL_TAG
      container_name: "${PROJECT_NAME}_mysql"
      entrypoint: ['/entrypoint.sh', '--default-authentication-plugin=mysql_native_password']
      environment:
        MYSQL_ROOT_PASSWORD: $DB_ROOT_PASSWORD
        MYSQL_USER: $DB_USER
        MYSQL_PASSWORD: $DB_PASSWORD
        MYSQL_DATABASE: $DB_NAME
      volumes:
        - "./drupal/mysql:/var/lib/mysql"
